<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\MngDocument.Application\MngDocument.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.12" />
    <PackageReference Include="Polly" Version="8.6.5" />
  </ItemGroup>
</Project>
