import type { Component } from 'vue';
import {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowRightIcon,
  BanIcon,
  BookmarkIcon,
  BoxIcon,
  BugIcon,
  CheckIcon,
  ChevronDownIcon,
  CircleCheckIcon,
  CircleDotIcon,
  CircleXIcon,
  ClockIcon,
  CodeIcon,
  EyeIcon,
  FlagIcon,
  HelpCircleIcon,
  HourglassIcon,
  LayoutKanbanIcon,
  ListCheckIcon,
  ListIcon,
  LockIcon,
  MinusIcon,
  PackageIcon,
  PencilIcon,
  PlayerPauseIcon,
  PlayerPlayIcon,
  ProgressIcon,
  RefreshIcon,
  RocketIcon,
  RotateClockwiseIcon,
  SparklesIcon,
  StarIcon,
  TruckIcon,
  UserCheckIcon,
  XIcon,
} from 'vue-tabler-icons';

/** Durum satırında saklanan değer = vue-tabler-icons export adı (örn. CircleDotIcon) */
export const TM_STATUS_TABLER_ICON_ENTRIES: ReadonlyArray<{ name: string; component: Component }> = [
  { name: 'CircleDotIcon', component: CircleDotIcon },
  { name: 'ListIcon', component: ListIcon },
  { name: 'ListCheckIcon', component: ListCheckIcon },
  { name: 'LayoutKanbanIcon', component: LayoutKanbanIcon },
  { name: 'ProgressIcon', component: ProgressIcon },
  { name: 'PlayerPlayIcon', component: PlayerPlayIcon },
  { name: 'PlayerPauseIcon', component: PlayerPauseIcon },
  { name: 'HourglassIcon', component: HourglassIcon },
  { name: 'ClockIcon', component: ClockIcon },
  { name: 'CircleCheckIcon', component: CircleCheckIcon },
  { name: 'CheckIcon', component: CheckIcon },
  { name: 'CircleXIcon', component: CircleXIcon },
  { name: 'XIcon', component: XIcon },
  { name: 'MinusIcon', component: MinusIcon },
  { name: 'ChevronDownIcon', component: ChevronDownIcon },
  { name: 'FlagIcon', component: FlagIcon },
  { name: 'BookmarkIcon', component: BookmarkIcon },
  { name: 'BoxIcon', component: BoxIcon },
  { name: 'StarIcon', component: StarIcon },
  { name: 'SparklesIcon', component: SparklesIcon },
  { name: 'RocketIcon', component: RocketIcon },
  { name: 'PackageIcon', component: PackageIcon },
  { name: 'TruckIcon', component: TruckIcon },
  { name: 'BugIcon', component: BugIcon },
  { name: 'AlertCircleIcon', component: AlertCircleIcon },
  { name: 'AlertTriangleIcon', component: AlertTriangleIcon },
  { name: 'BanIcon', component: BanIcon },
  { name: 'RefreshIcon', component: RefreshIcon },
  { name: 'RotateClockwiseIcon', component: RotateClockwiseIcon },
  { name: 'ArrowRightIcon', component: ArrowRightIcon },
  { name: 'PencilIcon', component: PencilIcon },
  { name: 'EyeIcon', component: EyeIcon },
  { name: 'LockIcon', component: LockIcon },
  { name: 'UserCheckIcon', component: UserCheckIcon },
  { name: 'CodeIcon', component: CodeIcon },
  { name: 'HelpCircleIcon', component: HelpCircleIcon },
];

export function getTmStatusTablerIconComponent(name: string | null | undefined): Component | null {
  if (!name?.trim()) return null;
  const n = name.trim();
  return TM_STATUS_TABLER_ICON_ENTRIES.find((x) => x.name === n)?.component ?? null;
}
